In [ ]:
# 파이썬 문법
# file, 파이썬에서 db다루기
# 웹크롤링..
# pandas

In [2]:
alist = [10, '20', 30, 40, 50]
type(alist)
alist

[10, '20', 30, 40, 50]

In [6]:
import numpy as np

np.array(alist)  
# 모든 요소는 같은 데이터 타입이어야한다.
# 데이터 타입의 우선순위가 있다. 자동변환

alist = [1,2,3,4,5]
arr = np.array(alist)
type(arr)
arr.dtype

dtype('int32')

In [8]:
A = np.array([1,2,3,4,5], dtype = np.float) # dtype 지정가능
A.dtype

dtype('float64')

In [9]:
A = np.array([1.2,2,3.4,4,5]) # 데이터를 보고 dtype이 변함
A.dtype

dtype('float64')

In [10]:
list(range(10)) # list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [11]:
np.arange(10) # array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
A = np.array([1.2,2,3.4,4,5])
A = A.astype(np.int32)         # FLOAT에서 INT32로 변경하기
A = A.astype(np.float64)       # int32에서 float로 변경하기
A

array([1., 2., 3., 4., 5.])

In [17]:
import timeit

In [20]:
# list 1 ~ 100 --> **2 (제곱하기 하는데 걸린 시간)
# 여러번 수행해서 평균을 낸다.

timeit.timeit('[i**2 for i in arr]',setup = 'arr =range(1, 101)')

41.005084500000066

In [22]:
timeit.timeit('arr**2', 'import numpy as np; arr = np.arange(1, 101)')

0.7851717999999437

timeit.timeit( ' 수행할문장 ' , ' 준비문장 ' )

In [ ]:
#numpy가 list보다 속도가 빠르다

In [23]:
np.array([1,2,3,4]) * 3    # 3배 계산

array([ 3,  6,  9, 12])

In [24]:
[1,2,3,4] * 3              # 반복

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [25]:
np.array([1,2,3,4]) + 100  # 각 항에 100씩 더하기

array([101, 102, 103, 104])

In [28]:
# 1차원 배열____ 대괄호의 개수를 보라
arr1 = np.array([1,2,3,4,5])
print(arr1.ndim, '차원이다')

1 차원이다


In [32]:
arr1.shape

(5,)

In [29]:
type((1,2))

tuple

In [30]:
type((1))

int

In [31]:
type((1,))

tuple

In [34]:
# 2차원 배열
arr2 = np.array([[1,2,3,4,5], [5,4,3,2,1]]) # 2행 5열
print(arr2.ndim, '차원이다')
print(arr2.shape, '모양')

2 차원이다
(2, 5) 모양


In [35]:
arr2 = np.array([[1,2,3,4,5], [5,4,3,2,1], [3,4,5,6]]) 
# 3행의 4열로 다른 행과 개수가 다르다
# 그래서 모양이 리스트가 되버린다. 2차원이 아니라 1차원

print(arr2.ndim, '차원이다')
print(arr2.shape, '모양')

1 차원이다
(3,) 모양


In [36]:
arr2 = np.array([
    [1,2,3,4,5], [5,4,3,2,1], [3,4,5,6, 9]
])  # 대괄호 안에 1차원이 3개
print(arr2.ndim, '차원이다')
print(arr2.shape, '모양')

2 차원이다
(3, 5) 모양


In [38]:
# 3차원

arr3 = np.array([
    [[1,2,3,4,5], [5,4,3,2,1], [3,4,5,6,9]],
    [[1,2,3,4,5], [5,4,3,2,1], [3,4,5,6,9]]
])     # 대괄호안에 2차원이 2개
print(arr3.ndim, '차원이다')
print(arr3.shape, '모양')    # 3행 5열이 2개 있다.

3 차원이다
(2, 3, 5) 모양


In [47]:
print(arr1.ndim, '차원')
print(arr1.shape, '모양')
print(len(arr1), '개수\n')

print(arr2.ndim, '차원')
print(arr2.shape, '모양')
print(len(arr2), '개수\n')

print(arr3.ndim, '차원')
print(arr3.shape, '모양')
print(len(arr3), '개수\n')
print(len(arr3[0]), '개\n')
print(len(arr3[0][0]), '개\n')
print((arr3[0][0][0]), '원소성분\n')
arr3[0,0,0] # 원소

1 차원
(5,) 모양
5 개수

2 차원
(3, 5) 모양
3 개수

3 차원
(2, 3, 5) 모양
2 개수

3 개

5 개

1 원소성분



1

In [49]:
np.array([5,6])

array([5, 6])

In [51]:
arr = np.zeros(5, dtype = np.int32) # default 는 float64
arr = np.zeros(5, dtype = 'U4')       # 최대 4자리
arr.dtype

dtype('<U4')

In [52]:
arr[0] = 'ABCDEFG'
arr

array(['ABCD', '', '', '', ''], dtype='<U4')

In [57]:
arr = np.zeros(5, dtype = np.int32) # default 는 float64
arr[0] = 2145555555
arr

array([2145555555,          0,          0,          0,          0])

In [59]:
arr = np.zeros((2, 3,2,4))
arr

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [60]:
arr = np.ones((3,2,4))
arr

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [64]:
arr = np.empty((5, 2,4))
arr

array([[[ 5.55329786e-321,  1.97626258e-323,  5.63234836e-321,
          1.97626258e-323],
        [ 5.77068674e-321,  1.97626258e-323,  0.00000000e+000,
          0.00000000e+000]],

       [[ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         -3.35811716e-311],
        [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
          0.00000000e+000]],

       [[ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
          0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         -1.63081252e-311]],

       [[ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         -3.99895963e-311],
        [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         -1.08758147e-311]],

       [[ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
          0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
          0.00000000e+000]]])

In [65]:
arr = np.full((3,2),4)
arr

array([[4, 4],
       [4, 4],
       [4, 4]])

In [66]:
arr = np.full(fill_value = 4, shape = (3,2))      # keyword value대로 값을 준다.
arr

array([[4, 4],
       [4, 4],
       [4, 4]])

# shift + tab >> 구문을 알 수 있다.

개발자도구 : ctrl + shift + c

In [69]:
arr = np.linspace(1, 10, 5)
arr # 1부터 10까지 5개 나온다. 간격은 2.25씩 증가

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [71]:
arr = np.array([1,2,3,4,5]) # 1차원임

arr.shape = 5, 1         # 5 by 1로 바꾸기

arr

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [80]:
arr3 = np.array([
    [[1,2,3], [4,5,6]],
                 [[10,20,30], [40,50,60]]
                ])
arr3.ndim                              # 3차원
arr3.shape                         # 2행 3열이 2개 있다.

(2, 2, 3)

In [81]:
arr3.shape[0], arr3.shape[1], arr3.shape[2]

(2, 2, 3)

In [86]:
for i in range(arr3.shape[0]):
    print('3차원이다리')
    for j in range(arr3.shape[1]):
        print('\t 2차원인뎅')
        for k in range(arr3.shape[2]):
            print('\t\t 1차원', arr3[i][j][k])

3차원이다리
	 2차원인뎅
		 1차원 1
		 1차원 2
		 1차원 3
	 2차원인뎅
		 1차원 4
		 1차원 5
		 1차원 6
3차원이다리
	 2차원인뎅
		 1차원 10
		 1차원 20
		 1차원 30
	 2차원인뎅
		 1차원 40
		 1차원 50
		 1차원 60


In [88]:
arr3 = np.array([[[1,2,3], [4,5,6]],
                [[10, 20, 30], [40, 50, 60]]
                ])
arr3.shape = 3, 4  # 3행 4열로 바꾸기

arr3

array([[ 1,  2,  3,  4],
       [ 5,  6, 10, 20],
       [30, 40, 50, 60]])

In [90]:
arr3 = np.array([[[1,2,3], [4,5,6]],
                [[10, 20, 30], [40, 50, 60]]
                ])

arr3.reshape(2, 6)

# reshape는 view, 원본은 변하지 않는다.

array([[ 1,  2,  3,  4,  5,  6],
       [10, 20, 30, 40, 50, 60]])

In [91]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 20, 30],
        [40, 50, 60]]])

In [97]:
arr3 = np.array([[[1,2,3], [4,5,6]],
                [[10, 20, 30], [40, 50, 60]]
                ])
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 20, 30],
        [40, 50, 60]]])

In [102]:
# reshape은 원본과 연결되어 있음
# 같은 주소, 서로의 변경이 적용된다.
B =arr3.reshape(2,6)

print(B.base) # 원본
print('------------------------')
B[0] = 99
arr3[1,1,2] = 66

print(B)
print(arr3)

[[[99 99 99]
  [99 99 99]]

 [[10 20 30]
  [40 50 66]]]
------------------------
[[99 99 99 99 99 99]
 [10 20 30 40 50 66]]
[[[99 99 99]
  [99 99 99]]

 [[10 20 30]
  [40 50 66]]]


In [105]:
arr3 = np.array([[[1,2,3], [4,5,6]],
                [[10, 20, 30], [40, 50, 60]]
                ])
C = arr3.reshape(2,6).copy()      # 서로 메모리 공간이 다르다
C.base                      # base는 없다.

C[1][5]= 999               # 하나의 변경이 다른쪽에 영향이 없다.
arr3

# 복사한 것이라 C랑 arr3 상관없다.

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 20, 30],
        [40, 50, 60]]])

In [106]:
arr3 = np.array([[[1,2,3], [4,5,6]],
                [[10, 20, 30], [40, 50, 60]]
                ])

arr3.reshape(6, -1)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [10, 20],
       [30, 40],
       [50, 60]])

In [108]:
arr3.reshape(-1, 6) # -1은 알아서 정하라는 것임

array([[ 1,  2,  3,  4,  5,  6],
       [10, 20, 30, 40, 50, 60]])

In [112]:
arr2 = np.array([[ 1,  2,  3,  4,  5,  6],
       [10, 20, 30, 40, 50, 60]])
arr2.reshape(3, -1, 2) # -1은 하나만 가능하다

# -1은 shape을 유추해서 결정한다의 의미

arr2.reshape(2,3,-1)
arr2.reshape(6, -1)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [10, 20],
       [30, 40],
       [50, 60]])

In [120]:
A = np.arange(16)
B = A.reshape(4, -1)
C = B.ravel()

print(C.base is B)
print(C.base is A)

False
True


In [123]:
A = np.arange(16)
A.resize(2, 8) # A가 2행 8열로 바뀜
A[0] = 88      # 0행이 88로 바뀜
A

array([[88, 88, 88, 88, 88, 88, 88, 88],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [127]:
A = np.array([[1, 2], [3, 4]])  # 2행2열
B = np.array([[5, 6], [7, 8]])  # 2행 2열

np.vstack((A, B))
np.hstack((A, B))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

# LAB
- ones, zeros, arange

In [144]:
a = np.zeros((3, 3))
b = np.ones((3, 2))
c = np.hstack((a, b))

d = np.arange(10, 160, 10).reshape(3, -1)
e = np.vstack((c,d))
result = np.vstack((e, e))
result

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [147]:
alist = [110., 120., 130., 140., 150.]
for val in alist:
    print(val)
    
for idx, val in enumerate(alist):
    print(idx+1, '>>>>', val)

110.0
120.0
130.0
140.0
150.0
1 >>>> 110.0
2 >>>> 120.0
3 >>>> 130.0
4 >>>> 140.0
5 >>>> 150.0


In [149]:
alist = [110., 120., 130., 140., 150.]
blist = [1,2,3,4,5]


list(zip(alist, blist))

[(110.0, 1), (120.0, 2), (130.0, 3), (140.0, 4), (150.0, 5)]

In [151]:
arr2 = np.array([[1,2,3,4,5,6],
                [10, 20, 30, 40, 50, 60]])

arr1 = arr2.reshape((12,))

array([ 1,  2,  3,  4,  5,  6, 10, 20, 30, 40, 50, 60])

In [154]:
arr1[0]
arr1[-1]
arr1[2:]
arr1[-2:]

arr2[0:]
arr2[-1]
arr2[1][3]
arr2[1, 3]
arr2[1][-3]

40

In [155]:
A = np.array([1,2,3,4])
B = np.array([11,12,13,14])

C = A.reshape((2, 2))
D = B.reshape((2, 2))

A+ B

array([12, 14, 16, 18])

In [156]:
C+D

array([[12, 14],
       [16, 18]])

In [157]:
A = np.array([1,2,3,4, 5, 6])
B = np.array([11,12,13,14, 15,16])

C = A.reshape((2, 3))
D = B.reshape((2, 3))

A+ B
C+D

array([[12, 14, 16],
       [18, 20, 22]])

In [160]:
A = np.arange(12).reshape((3,4))
B = np.array([10,20,30,40])
print(A.shape)
print(B.shape)  # 뒤에가 4로 같아서 연산이 가능하다

print(A)
print(B)

A + B    # BROADCASTING

(3, 4)
(4,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[10 20 30 40]


array([[10, 21, 32, 43],
       [14, 25, 36, 47],
       [18, 29, 40, 51]])

In [167]:
A =np.arange(10, 250, 10).reshape(2, 3, 4)
B =np.arange(1, 13, 1).reshape(3,4)

A + B

array([[[ 11,  22,  33,  44],
        [ 55,  66,  77,  88],
        [ 99, 110, 121, 132]],

       [[131, 142, 153, 164],
        [175, 186, 197, 208],
        [219, 230, 241, 252]]])

In [169]:
A =np.arange(10, 1210, 10).reshape(2, 3, 4, 5)   # 4행 5열
B =np.arange(1, 21, 1).reshape(4,5)

A

array([[[[  10,   20,   30,   40,   50],
         [  60,   70,   80,   90,  100],
         [ 110,  120,  130,  140,  150],
         [ 160,  170,  180,  190,  200]],

        [[ 210,  220,  230,  240,  250],
         [ 260,  270,  280,  290,  300],
         [ 310,  320,  330,  340,  350],
         [ 360,  370,  380,  390,  400]],

        [[ 410,  420,  430,  440,  450],
         [ 460,  470,  480,  490,  500],
         [ 510,  520,  530,  540,  550],
         [ 560,  570,  580,  590,  600]]],


       [[[ 610,  620,  630,  640,  650],
         [ 660,  670,  680,  690,  700],
         [ 710,  720,  730,  740,  750],
         [ 760,  770,  780,  790,  800]],

        [[ 810,  820,  830,  840,  850],
         [ 860,  870,  880,  890,  900],
         [ 910,  920,  930,  940,  950],
         [ 960,  970,  980,  990, 1000]],

        [[1010, 1020, 1030, 1040, 1050],
         [1060, 1070, 1080, 1090, 1100],
         [1110, 1120, 1130, 1140, 1150],
         [1160, 1170, 1180, 1190, 1200]]]])

In [171]:
# broad casting
# 작은 배열의 차원을 큰 사이즈의 배열의 마지막에 매칭
# 매칭되면 나머지 차원은 복사 ............         매칭 되면, 크기가 달라도 연산가능
A = np.arange(10, 1210, 10).reshape(2, 3, 4, 5)   # 4행 5열
B = np.arange(1, 6, 1)                            # 1 차원     -- (5, )
B = np.arange(1, 21, 1).reshape(4, 5)             # 2 차원    -- (4, 5)
B = np.arange(1, 61, 1).reshape(3, 4, 5)          # 3 차원
B = np.arange(1, 121, 1).reshape(2, 3, 4, 5)      # 4 차원
A + B

array([[[[  11,   22,   33,   44,   55],
         [  66,   77,   88,   99,  110],
         [ 121,  132,  143,  154,  165],
         [ 176,  187,  198,  209,  220]],

        [[ 231,  242,  253,  264,  275],
         [ 286,  297,  308,  319,  330],
         [ 341,  352,  363,  374,  385],
         [ 396,  407,  418,  429,  440]],

        [[ 451,  462,  473,  484,  495],
         [ 506,  517,  528,  539,  550],
         [ 561,  572,  583,  594,  605],
         [ 616,  627,  638,  649,  660]]],


       [[[ 611,  622,  633,  644,  655],
         [ 666,  677,  688,  699,  710],
         [ 721,  732,  743,  754,  765],
         [ 776,  787,  798,  809,  820]],

        [[ 831,  842,  853,  864,  875],
         [ 886,  897,  908,  919,  930],
         [ 941,  952,  963,  974,  985],
         [ 996, 1007, 1018, 1029, 1040]],

        [[1051, 1062, 1073, 1084, 1095],
         [1106, 1117, 1128, 1139, 1150],
         [1161, 1172, 1183, 1194, 1205],
         [1216, 1227, 1238, 1249, 1260]]]])

벡터의 연산

In [172]:
A = np.arange(1, 10001)
B = np.arange(10001, 20001)

Z = A + B
Z

array([10002, 10004, 10006, ..., 29996, 29998, 30000])

In [176]:
A = np.array([1,2,3,4,5])
B = np.array([6,2,7,4,8])

A == B
A <= B

np.all(A >= B)  # LOOP 돌릴 필요가 없다

False

In [177]:
arr = np.array([1,2,3,4,5])
np.random.choice(arr, 3, replace = False)

In [207]:
np.random.choice(5, 3, replace = False)

array([4, 1, 3])

In [220]:
np.random.choice(5, 10) # 반복해서 10개 생성

array([4, 1, 0, 3, 4, 3, 3, 2, 1, 3])

In [221]:
np.random.choice(arr, 10) # 반복해서 10개 생성

array([2, 1, 3, 4, 2, 4, 1, 2, 2, 1])

In [234]:
np.random.choice(5, 10, p =[0.1, 0, 0.3, 0.6, 0]) # 선택확률을 다르게 해서 10개 추출

array([3, 3, 0, 3, 3, 3, 3, 3, 3, 3], dtype=int64)

In [236]:
np.random.rand(3, 5) # shape = 3 by 5

array([[0.78281741, 0.48857563, 0.49744069, 0.85044879, 0.06451981],
       [0.98661685, 0.47985551, 0.6225245 , 0.67548393, 0.59872555],
       [0.31989008, 0.29922206, 0.26996238, 0.0727183 , 0.29035863]])

In [247]:
np.random.rand(3) 

array([0.75946599, 0.16478693, 0.0418604 ])

In [256]:
np.random.randint(10)

4

In [264]:
np.random.randint(1, 10, size = 5)

array([9, 6, 2, 8, 3])

In [278]:
np.random.randint(1, 45, size = (2,4))

array([[28, 16, 44, 33],
       [41, 35, 29, 27]])

In [277]:
np.random.rand(6)

array([0.8536235 , 0.79491282, 0.46611563, 0.62619965, 0.894773  ,
       0.95220624])

In [281]:
A = np.array([1,2,3,10,20,30])
index = np.where(A >= 10)
A[index]

array([10, 20, 30])

In [283]:
A[[2, 5]]

A[np.where(A%3 == 0)]

array([ 3, 30])

In [284]:
A =np.array([1,2,3,10,20,30])

np.where(A > 20)

(array([5], dtype=int64),)

In [286]:
A >= 20

array([False, False, False, False,  True,  True])

In [287]:
A[[False, False, False, False,  True,  True]]

array([20, 30])

In [288]:
A[np.where(A >= 20)]

array([20, 30])

In [289]:
np.where(A >= 20, '크다', '작다')

array(['작다', '작다', '작다', '작다', '크다', '크다'], dtype='<U2')

In [296]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,1,2,3],[10,20,30,40],[50,60,70,80],[90,10,20,30]])

x, y = np.split(arr, [3], axis=0) # 앞에꺼 3개, 뒤에꺼 3개 총 2개로 나뉜다.
x, y = np.vsplit(arr, [3])        # axis = 0 들어있음

x, y = np.split(arr, [2], axis=1)
x, y = np.hsplit(arr, [2])         # axis = 1 들어있음

print('x', x)
print('y', y)

x [[ 1  2]
 [ 5  6]
 [ 9  1]
 [10 20]
 [50 60]
 [90 10]]
y [[ 3  4]
 [ 7  8]
 [ 2  3]
 [30 40]
 [70 80]
 [20 30]]


In [297]:
np.add.accumulate(x)

array([[  1,   2],
       [  6,   8],
       [ 15,   9],
       [ 25,  29],
       [ 75,  89],
       [165,  99]], dtype=int32)

In [299]:
x, y = np.split(arr, [3], axis=0)
print('x', x)
print('y', y)

x [[1 2 3 4]
 [5 6 7 8]
 [9 1 2 3]]
y [[10 20 30 40]
 [50 60 70 80]
 [90 10 20 30]]


In [300]:
np.add.accumulate(x)

array([[ 1,  2,  3,  4],
       [ 6,  8, 10, 12],
       [15,  9, 12, 15]], dtype=int32)

In [301]:
np.sum(x)

51

In [302]:
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 1, 2, 3]])

In [303]:
np.mean(x)

4.25

# pandas : python library = series + dataframe

In [305]:
import pandas as pd

In [306]:
!conda list numpy

# packages in environment at C:\Users\student\Anaconda3:
#
# Name                    Version                   Build  Channel
numpy                     1.16.5           py37h19fb1c0_0  
numpy-base                1.16.5           py37hc3f5095_0  
numpydoc                  0.9.1                      py_0  


In [319]:
df = pd.read_csv("data/gapminder.tsv", sep='\t')

# ../../       -- 올라가는 것

In [320]:
df.tail()

country continent  year  lifeExp       pop   gdpPercap
1699  Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700  Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701  Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702  Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703  Zimbabwe    Africa  2007   43.487  12311143  469.709298

In [323]:
df.columns

Index(['country', 'continent', 'year', 'lifeExp', 'pop', 'gdpPercap'], dtype='object')

In [324]:
df.shape

(1704, 6)

In [326]:
df.info()

# object -- 문자(pandas에서는 그렇게 함)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
country      1704 non-null object
continent    1704 non-null object
year         1704 non-null int64
lifeExp      1704 non-null float64
pop          1704 non-null int64
gdpPercap    1704 non-null float64
dtypes: float64(2), int64(2), object(2)
memory usage: 80.0+ KB


p35 python의 string == pandas의 object

In [334]:
s = df['country']
# series들의 집합 == dataframe

type(s)

pandas.core.series.Series

In [335]:
s.head(3)

0    Afghanistan
1    Afghanistan
2    Afghanistan
Name: country, dtype: object

In [336]:
df.head(3)

country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710

In [346]:
type(df.loc[1])

pandas.core.series.Series

In [347]:
df.loc[1, 'year']      # index와 column명으로 추출하기

1957

In [348]:
df.loc[0, 'lifeExp']

28.801

In [349]:
type(df.iloc[1])       # row번호와 행번호로 가져오기

pandas.core.series.Series

In [350]:
df.iloc[1, 2]

1957

p39. index로 가져오기 등

In [351]:
df.index

RangeIndex(start=0, stop=1704, step=1)

In [354]:
# df.loc[-1]   존재하는 index가 없으면 오류
df.iloc[-1]    # row 번호.... 마지막이 -1

# 이건 series 형..

country      Zimbabwe
continent      Africa
year             2007
lifeExp        43.487
pop          12311143
gdpPercap     469.709
Name: 1703, dtype: object

In [357]:
# 5, 10, 15, 20

df.loc[[5, 10, 15, 20]]
df.iloc[[5, 10, 15, 20]]

country continent  year  lifeExp       pop    gdpPercap
5   Afghanistan      Asia  1977   38.438  14880372   786.113360
10  Afghanistan      Asia  2002   42.129  25268405   726.734055
15      Albania    Europe  1967   66.220   1984060  2760.196931
20      Albania    Europe  1992   71.581   3326498  2497.437901

In [359]:
df.loc[[1,2,3],[ "year"]] # 데이터프레임

year
1  1957
2  1962
3  1967

In [360]:
df.loc[[1,2,3], "year"] # 시리즈

1    1957
2    1962
3    1967
Name: year, dtype: int64

In [363]:
df.loc[[1,2,3],[ "year", "country"]]
df.loc[ : ,[ "year", "country"]]

year      country
0     1952  Afghanistan
1     1957  Afghanistan
2     1962  Afghanistan
3     1967  Afghanistan
4     1972  Afghanistan
...    ...          ...
1699  1987     Zimbabwe
1700  1992     Zimbabwe
1701  1997     Zimbabwe
1702  2002     Zimbabwe
1703  2007     Zimbabwe

[1704 rows x 2 columns]

In [373]:
df.iloc[[1,2,3, -1],[0, 1, 2, -1]]
df.iloc[: , [0, 1,2, -1]]
df.iloc[:, :]
df.head(2)

country continent  year  lifeExp      pop   gdpPercap
0  Afghanistan      Asia  1952   28.801  8425333  779.445314
1  Afghanistan      Asia  1957   30.332  9240934  820.853030

In [372]:
# 연도별로 평균수명을 묶어라
df.groupby('year')['lifeExp'].mean()

year
1952    49.057620
1957    51.507401
1962    53.609249
1967    55.678290
1972    57.647386
1977    59.570157
1982    61.533197
1987    63.212613
1992    64.160338
1997    65.014676
2002    65.694923
2007    67.007423
Name: lifeExp, dtype: float64

In [374]:
df.columns

Index(['country', 'continent', 'year', 'lifeExp', 'pop', 'gdpPercap'], dtype='object')

In [376]:
df.groupby(['year', 'continent'])['lifeExp', 'gdpPercap'].mean()

lifeExp     gdpPercap
year continent                         
1952 Africa     39.135500   1252.572466
     Americas   53.279840   4079.062552
     Asia       46.314394   5195.484004
     Europe     64.408500   5661.057435
     Oceania    69.255000  10298.085650
1957 Africa     41.266346   1385.236062
     Americas   55.960280   4616.043733
     Asia       49.318544   5787.732940
     Europe     66.703067   6963.012816
     Oceania    70.295000  11598.522455
1962 Africa     43.319442   1598.078825
     Americas   58.398760   4901.541870
     Asia       51.563223   5729.369625
     Europe     68.539233   8365.486814
     Oceania    71.085000  12696.452430
1967 Africa     45.334538   2050.363801
     Americas   60.410920   5668.253496
     Asia       54.663640   5971.173374
     Europe     69.737600  10143.823757
     Oceania    71.310000  14495.021790
1972 Africa     47.450942   2339.615674
     Americas   62.394920   6491.334139
     Asia       57.319269   8187.468699
     Europe     70.775033  12479.575246
     Oceania    71.910000  16417.333380
1977 Africa     49.580423   2585.938508
     Americas   64.391560   7352.007126
     Asia       59.610556   7791.314020
     Europe     71.937767  14283.979110
     Oceania    72.855000  17283.957605
1982 Africa     51.592865   2481.592960
     Americas   66.228840   7506.737088
     Asia       62.617939   7434.135157
     Europe     72.806400  15617.896551
     Oceania    74.290000  18554.709840
1987 Africa     53.344788   2282.668991
     Americas   68.090720   7793.400261
     Asia       64.851182   7608.226508
     Europe     73.642167  17214.310727
     Oceania    75.320000  20448.040160
1992 Africa     53.629577   2281.810333
     Americas   69.568360   8044.934406
     Asia       66.537212   8639.690248
     Europe     74.440100  17061.568084
     Oceania    76.945000  20894.045885
1997 Africa     53.598269   2378.759555
     Americas   71.150480   8889.300863
     Asia       68.020515   9834.093295
     Europe     75.505167  19076.781802
     Oceania    78.190000  24024.175170
2002 Africa     53.325231   2599.385159
     Americas   72.422040   9287.677107
     Asia       69.233879  10174.090397
     Europe     76.700600  21711.732422
     Oceania    79.740000  26938.778040
2007 Africa     54.806038   3089.032605
     Americas   73.608120  11003.031625
     Asia       70.728485  12473.026870
     Europe     77.648600  25054.481636
     Oceania    80.719500  29810.188275

In [377]:
df.groupby(['year', 'continent'])['lifeExp', 'pop', 'gdpPercap'].mean()

lifeExp           pop     gdpPercap
year continent                                       
1952 Africa     39.135500  4.570010e+06   1252.572466
     Americas   53.279840  1.380610e+07   4079.062552
     Asia       46.314394  4.228356e+07   5195.484004
     Europe     64.408500  1.393736e+07   5661.057435
     Oceania    69.255000  5.343003e+06  10298.085650
1957 Africa     41.266346  5.093033e+06   1385.236062
     Americas   55.960280  1.547816e+07   4616.043733
     Asia       49.318544  4.735699e+07   5787.732940
     Europe     66.703067  1.459635e+07   6963.012816
     Oceania    70.295000  5.970988e+06  11598.522455
1962 Africa     43.319442  5.702247e+06   1598.078825
     Americas   58.398760  1.733081e+07   4901.541870
     Asia       51.563223  5.140476e+07   5729.369625
     Europe     68.539233  1.534517e+07   8365.486814
     Oceania    71.085000  6.641759e+06  12696.452430
1967 Africa     45.334538  6.447875e+06   2050.363801
     Americas   60.410920  1.922986e+07   5668.253496
     Asia       54.663640  5.774736e+07   5971.173374
     Europe     69.737600  1.603930e+07  10143.823757
     Oceania    71.310000  7.300207e+06  14495.021790
1972 Africa     47.450942  7.305376e+06   2339.615674
     Americas   62.394920  2.117537e+07   6491.334139
     Asia       57.319269  6.518098e+07   8187.468699
     Europe     70.775033  1.668784e+07  12479.575246
     Oceania    71.910000  8.053050e+06  16417.333380
1977 Africa     49.580423  8.328097e+06   2585.938508
     Americas   64.391560  2.312271e+07   7352.007126
     Asia       59.610556  7.225799e+07   7791.314020
     Europe     71.937767  1.723882e+07  14283.979110
     Oceania    72.855000  8.619500e+06  17283.957605
1982 Africa     51.592865  9.602857e+06   2481.592960
     Americas   66.228840  2.521164e+07   7506.737088
     Asia       62.617939  7.909502e+07   7434.135157
     Europe     72.806400  1.770890e+07  15617.896551
     Oceania    74.290000  9.197425e+06  18554.709840
1987 Africa     53.344788  1.105450e+07   2282.668991
     Americas   68.090720  2.731016e+07   7793.400261
     Asia       64.851182  8.700669e+07   7608.226508
     Europe     73.642167  1.810314e+07  17214.310727
     Oceania    75.320000  9.787208e+06  20448.040160
1992 Africa     53.629577  1.267464e+07   2281.810333
     Americas   69.568360  2.957096e+07   8044.934406
     Asia       66.537212  9.494825e+07   8639.690248
     Europe     74.440100  1.860476e+07  17061.568084
     Oceania    76.945000  1.045983e+07  20894.045885
1997 Africa     53.598269  1.430448e+07   2378.759555
     Americas   71.150480  3.187602e+07   8889.300863
     Asia       68.020515  1.025238e+08   9834.093295
     Europe     75.505167  1.896480e+07  19076.781802
     Oceania    78.190000  1.112072e+07  24024.175170
2002 Africa     53.325231  1.603315e+07   2599.385159
     Americas   72.422040  3.399091e+07   9287.677107
     Asia       69.233879  1.091455e+08  10174.090397
     Europe     76.700600  1.927413e+07  21711.732422
     Oceania    79.740000  1.172741e+07  26938.778040
2007 Africa     54.806038  1.787576e+07   3089.032605
     Americas   73.608120  3.595485e+07  11003.031625
     Asia       70.728485  1.155138e+08  12473.026870
     Europe     77.648600  1.953662e+07  25054.481636
     Oceania    80.719500  1.227497e+07  29810.188275

In [378]:
df.groupby(['year'])['lifeExp', 'pop', 'gdpPercap'].mean()

lifeExp           pop     gdpPercap
year                                       
1952  49.057620  1.695040e+07   3725.276046
1957  51.507401  1.876341e+07   4299.408345
1962  53.609249  2.042101e+07   4725.812342
1967  55.678290  2.265830e+07   5483.653047
1972  57.647386  2.518998e+07   6770.082815
1977  59.570157  2.767638e+07   7313.166421
1982  61.533197  3.020730e+07   7518.901673
1987  63.212613  3.303857e+07   7900.920218
1992  64.160338  3.599092e+07   8158.608521
1997  65.014676  3.883947e+07   9090.175363
2002  65.694923  4.145759e+07   9917.848365
2007  67.007423  4.402122e+07  11680.071820

In [379]:
df.groupby(['continent'])['lifeExp'].mean()

continent
Africa      48.865330
Americas    64.658737
Asia        60.064903
Europe      71.903686
Oceania     74.326208
Name: lifeExp, dtype: float64

In [381]:
df.groupby(['continent','year'])[['lifeExp']].mean() #lifeExp 에 대괄호 다시 치기,,,,, 데이터 프레임형태로 출력함

lifeExp
continent year           
Africa    1952  39.135500
          1957  41.266346
          1962  43.319442
          1967  45.334538
          1972  47.450942
          1977  49.580423
          1982  51.592865
          1987  53.344788
          1992  53.629577
          1997  53.598269
          2002  53.325231
          2007  54.806038
Americas  1952  53.279840
          1957  55.960280
          1962  58.398760
          1967  60.410920
          1972  62.394920
          1977  64.391560
          1982  66.228840
          1987  68.090720
          1992  69.568360
          1997  71.150480
          2002  72.422040
          2007  73.608120
Asia      1952  46.314394
          1957  49.318544
          1962  51.563223
          1967  54.663640
          1972  57.319269
          1977  59.610556
          1982  62.617939
          1987  64.851182
          1992  66.537212
          1997  68.020515
          2002  69.233879
          2007  70.728485
Europe    1952  64.408500
          1957  66.703067
          1962  68.539233
          1967  69.737600
          1972  70.775033
          1977  71.937767
          1982  72.806400
          1987  73.642167
          1992  74.440100
          1997  75.505167
          2002  76.700600
          2007  77.648600
Oceania   1952  69.255000
          1957  70.295000
          1962  71.085000
          1967  71.310000
          1972  71.910000
          1977  72.855000
          1982  74.290000
          1987  75.320000
          1992  76.945000
          1997  78.190000
          2002  79.740000
          2007  80.719500

In [385]:
df.groupby(['continent'])['country'].nunique() # unique의 갯수 
# 대륙별로 그룹을 짓고, 그 안에 여러 나라별 유니크한 것의 개수

continent
Africa      52
Americas    25
Asia        33
Europe      30
Oceania      2
Name: country, dtype: int64

In [395]:
df['continent'] == 'Africa' # 인것의 row를 가져와야한다.

0       False
1       False
2       False
3       False
4       False
        ...  
1699     True
1700     True
1701     True
1702     True
1703     True
Name: continent, Length: 1704, dtype: bool

In [ ]:
# iloc은 인덱스, loc은 순서

In [404]:
df[df.continent == 'Africa']['country'].nunique()

52

df [ [ True , True , True , True , True , True ] ]

In [400]:
df[df.continent =='Asia'] # 나라

country continent  year  lifeExp       pop    gdpPercap
0     Afghanistan      Asia  1952   28.801   8425333   779.445314
1     Afghanistan      Asia  1957   30.332   9240934   820.853030
2     Afghanistan      Asia  1962   31.997  10267083   853.100710
3     Afghanistan      Asia  1967   34.020  11537966   836.197138
4     Afghanistan      Asia  1972   36.088  13079460   739.981106
...           ...       ...   ...      ...       ...          ...
1675  Yemen, Rep.      Asia  1987   52.922  11219340  1971.741538
1676  Yemen, Rep.      Asia  1992   55.599  13367997  1879.496673
1677  Yemen, Rep.      Asia  1997   58.020  15826497  2117.484526
1678  Yemen, Rep.      Asia  2002   60.308  18701257  2234.820827
1679  Yemen, Rep.      Asia  2007   62.698  22211743  2280.769906

[396 rows x 6 columns]

In [403]:
df[df.continent =='Asia']['country'].unique() # array 형태로 나온다.

array(['Afghanistan', 'Bahrain', 'Bangladesh', 'Cambodia', 'China',
       'Hong Kong, China', 'India', 'Indonesia', 'Iran', 'Iraq', 'Israel',
       'Japan', 'Jordan', 'Korea, Dem. Rep.', 'Korea, Rep.', 'Kuwait',
       'Lebanon', 'Malaysia', 'Mongolia', 'Myanmar', 'Nepal', 'Oman',
       'Pakistan', 'Philippines', 'Saudi Arabia', 'Singapore',
       'Sri Lanka', 'Syria', 'Taiwan', 'Thailand', 'Vietnam',
       'West Bank and Gaza', 'Yemen, Rep.'], dtype=object)

In [405]:
len(df[df.continent =='Asia']['country'].unique())

33

In [407]:
df[df.continent =='Asia']['country'].nunique()

33

In [413]:
# !pip install matplotlib # 설치

In [415]:
import matplotlib.pyplot as plt

s = df.groupby('year')['lifeExp'].mean()
s.plot()

#연도가 증가하면서 기대수명이 증가한다.

In [417]:
s1 = pd.Series(['banana', 42], index= ['괄이름', '물량'])
s1

괄이름    banana
물량         42
dtype: object

In [418]:
s1[1]
s1['물량']

42

In [425]:
df = pd.DataFrame({'Name' : ['가가가', '나나나', '다다다'],
             'job' : ['학생',' 선생', '기자'],
              
              'age' : [10, 20, 30]
             })
df

Name  job  age
0  가가가   학생   10
1  나나나   선생   20
2  다다다   기자   30

In [426]:
# index 이용
df.loc[0]
df.loc[0, 'Name']


# 순서 이용
df.iloc[0, 1]
df.iloc[0]

Name    가가가
job      학생
age      10
Name: 0, dtype: object